/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Symbol = IDL.Text;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Category = IDL.Variant({
  'metal' : IDL.Null,
  'stock' : IDL.Null,
  'crypto' : IDL.Null,
  'index' : IDL.Null,
});
export const Asset = IDL.Record({
  'change24h' : IDL.Float64,
  'name' : IDL.Text,
  'category' : Category,
  'price' : IDL.Float64,
  'symbol' : Symbol,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const PortfolioAsset = IDL.Record({
  'currentPrice' : IDL.Float64,
  'totalValue' : IDL.Float64,
  'quantity' : IDL.Float64,
  'symbol' : Symbol,
});
export const TradeType = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
export const PublicTrade = IDL.Record({
  'total' : IDL.Float64,
  'tradeType' : TradeType,
  'pricePerUnit' : IDL.Float64,
  'timestamp' : IDL.Int,
  'quantity' : IDL.Float64,
  'symbol' : Symbol,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addToWatchlist' : IDL.Func([Symbol], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'buy' : IDL.Func([Symbol, IDL.Float64], [], []),
  'getAllAssets' : IDL.Func([], [IDL.Vec(Asset)], []),
  'getAsset' : IDL.Func([Symbol], [Asset], ['query']),
  'getBalance' : IDL.Func([], [IDL.Float64], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPortfolio' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(Symbol, IDL.Float64))],
      ['query'],
    ),
  'getPortfolioAssets' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(PortfolioAsset)],
      ['query'],
    ),
  'getTrades' : IDL.Func([], [IDL.Vec(PublicTrade)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWatchlist' : IDL.Func([], [IDL.Vec(Symbol)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeFromWatchlist' : IDL.Func([Symbol], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sell' : IDL.Func([Symbol, IDL.Float64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Symbol = IDL.Text;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Category = IDL.Variant({
    'metal' : IDL.Null,
    'stock' : IDL.Null,
    'crypto' : IDL.Null,
    'index' : IDL.Null,
  });
  const Asset = IDL.Record({
    'change24h' : IDL.Float64,
    'name' : IDL.Text,
    'category' : Category,
    'price' : IDL.Float64,
    'symbol' : Symbol,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const PortfolioAsset = IDL.Record({
    'currentPrice' : IDL.Float64,
    'totalValue' : IDL.Float64,
    'quantity' : IDL.Float64,
    'symbol' : Symbol,
  });
  const TradeType = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
  const PublicTrade = IDL.Record({
    'total' : IDL.Float64,
    'tradeType' : TradeType,
    'pricePerUnit' : IDL.Float64,
    'timestamp' : IDL.Int,
    'quantity' : IDL.Float64,
    'symbol' : Symbol,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addToWatchlist' : IDL.Func([Symbol], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'buy' : IDL.Func([Symbol, IDL.Float64], [], []),
    'getAllAssets' : IDL.Func([], [IDL.Vec(Asset)], []),
    'getAsset' : IDL.Func([Symbol], [Asset], ['query']),
    'getBalance' : IDL.Func([], [IDL.Float64], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPortfolio' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(Symbol, IDL.Float64))],
        ['query'],
      ),
    'getPortfolioAssets' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(PortfolioAsset)],
        ['query'],
      ),
    'getTrades' : IDL.Func([], [IDL.Vec(PublicTrade)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWatchlist' : IDL.Func([], [IDL.Vec(Symbol)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeFromWatchlist' : IDL.Func([Symbol], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sell' : IDL.Func([Symbol, IDL.Float64], [], []),
  });
};

export const init = ({ IDL }) => { return []; };