/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Asset {
  'change24h' : number,
  'name' : string,
  'category' : Category,
  'price' : number,
  'symbol' : Symbol,
}
export type Category = { 'metal' : null } |
  { 'stock' : null } |
  { 'crypto' : null } |
  { 'index' : null };
export interface PortfolioAsset {
  'currentPrice' : number,
  'totalValue' : number,
  'quantity' : number,
  'symbol' : Symbol,
}
export interface PublicTrade {
  'total' : number,
  'tradeType' : TradeType,
  'pricePerUnit' : number,
  'timestamp' : bigint,
  'quantity' : number,
  'symbol' : Symbol,
}
export type Symbol = string;
export type TradeType = { 'buy' : null } |
  { 'sell' : null };
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addToWatchlist' : ActorMethod<[Symbol], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'buy' : ActorMethod<[Symbol, number], undefined>,
  'getAllAssets' : ActorMethod<[], Array<Asset>>,
  'getAsset' : ActorMethod<[Symbol], Asset>,
  'getBalance' : ActorMethod<[], number>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPortfolio' : ActorMethod<[], Array<[Symbol, number]>>,
  'getPortfolioAssets' : ActorMethod<[[] | [string]], Array<PortfolioAsset>>,
  'getTrades' : ActorMethod<[], Array<PublicTrade>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWatchlist' : ActorMethod<[], Array<Symbol>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeFromWatchlist' : ActorMethod<[Symbol], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sell' : ActorMethod<[Symbol, number], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];